export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  PAYLOAD_TOO_LARGE: 413,
  UNSUPPORTED_MEDIA_TYPE: 415,
  INTERNAL_SERVER_ERROR: 500,
};

export const ERROR_CODES = {
  FILE_SIZE_EXCEEDED: "FILE_SIZE_EXCEEDED",
  FILE_TYPE_NOT_SUPPORTED: "FILE_TYPE_NOT_SUPPORTED",
  FILE_NAME_INVALID: "FILE_NAME_INVALID",
  FILE_NOT_PROVIDED: "FILE_NOT_PROVIDED",

  REQUEST_VALIDATION_ERROR: "REQUEST_VALIDATION_ERROR",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",

  SERVER_ERROR: "SERVER_ERROR",

  DB_ERROR: "DB_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
};
